'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { IconEdit, IconNote, IconTag } from '@tabler/icons-react';

export function CustomerActions({ customerId, profile }: { customerId: string; profile: { full_name: string | null; email: string | null; phone: string | null } }) {
  const router = useRouter(); const [mode,setMode]=useState<'edit'|'note'|'tag'|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const data=new FormData(event.currentTarget);
    const endpoint=mode==='edit'?`/api/admin/clients/${customerId}`:mode==='note'?`/api/admin/clients/${customerId}/notes`:`/api/admin/clients/${customerId}/tags`;
    const body=mode==='edit'?{fullName:data.get('fullName')||null,email:data.get('email')||null,phone:data.get('phone')||null}:mode==='note'?{body:data.get('body')}:{name:data.get('name')};
    const response=await fetch(endpoint,{method:mode==='edit'?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const result=await response.json(); setBusy(false);
    if(!response.ok){setError(result.error??'Action impossible.');return;} setMode(null); router.refresh();
  }
  return <><div className="flex flex-wrap gap-2"><button onClick={()=>setMode('edit')} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[var(--admin-border)] bg-white px-4 text-sm font-semibold dark:bg-gray-900"><IconEdit size={17}/>Modifier</button><button onClick={()=>setMode('note')} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[var(--admin-border)] bg-white px-4 text-sm font-semibold dark:bg-gray-900"><IconNote size={17}/>Ajouter une note</button><button onClick={()=>setMode('tag')} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[var(--admin-border)] bg-white px-4 text-sm font-semibold dark:bg-gray-900"><IconTag size={17}/>Ajouter un tag</button></div>{mode&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-4" onMouseDown={()=>setMode(null)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()} className="w-full space-y-3 rounded-t-3xl bg-white p-5 dark:bg-gray-900 sm:max-w-md sm:rounded-2xl"><h2 className="text-lg font-semibold">{mode==='edit'?'Modifier le client':mode==='note'?'Ajouter une note':'Ajouter un tag'}</h2>{mode==='edit'&&<><input name="fullName" defaultValue={profile.full_name??''} placeholder="Nom" className="h-11 w-full rounded-xl border px-3 dark:bg-gray-950"/><input name="email" type="email" defaultValue={profile.email??''} placeholder="E-mail" className="h-11 w-full rounded-xl border px-3 dark:bg-gray-950"/><input name="phone" defaultValue={profile.phone??''} placeholder="Téléphone" className="h-11 w-full rounded-xl border px-3 dark:bg-gray-950"/></>}{mode==='note'&&<textarea name="body" required maxLength={4000} rows={5} placeholder="Note interne…" className="w-full rounded-xl border p-3 dark:bg-gray-950"/>}{mode==='tag'&&<input name="name" required maxLength={60} placeholder="Ex. Grossiste" className="h-11 w-full rounded-xl border px-3 dark:bg-gray-950"/>}{error&&<p className="text-sm text-red-600">{error}</p>}<div className="flex gap-2"><button type="button" onClick={()=>setMode(null)} className="min-h-11 flex-1 rounded-xl border px-4">Annuler</button><button disabled={busy} className="min-h-11 flex-1 rounded-xl bg-[var(--admin-primary)] px-4 font-semibold text-white disabled:opacity-50">{busy?'Enregistrement…':'Enregistrer'}</button></div></form></div>}</>;
}
