'use client';

import { useState } from 'react';
import { IconArrowLeft,IconBuildingBank,IconCash,IconBrandPaypal,IconQrcode,IconWallet,IconCreditCard,IconCopy,IconCheck,IconChevronRight,IconExternalLink } from '@tabler/icons-react';
import { PAYMENT_METHOD_REGISTRY, type TenantPaymentMethod } from '@lepefy/types';
import { CardQuickPay } from './CardQuickPay';
import { methodColor, hexToRgba, isEmailValue } from '@/lib/card/methodColor';

const PAYMENT_ICONS={IconBuildingBank,IconCash,IconBrandPaypal,IconQrcode,IconWallet,IconCreditCard};
type Lang='fr'|'it';
const COPY={
 fr:{title:'Moyens de paiement',back:'Retour',card:'Paiement sécurisé par Stripe',bank:'IBAN / BIC',paypal:'Paiement via PayPal',satispay:'Paiement via Satispay',revolut:'Paiement via Revolut',cash:'Paiement en boutique',other:'Moyen de paiement alternatif',beneficiary:'Bénéficiaire',copy:'Copier',copied:'Copié !',bankTitle:'Virement bancaire',cashTitle:'Paiement en espèces',cashText:'Les espèces sont acceptées directement en boutique.',externalText:'Vous allez continuer dans l’application ou le site du service de paiement.',open:(x:string)=>`Ouvrir ${x}`},
 it:{title:'Metodi di pagamento',back:'Indietro',card:'Pagamento sicuro con Stripe',bank:'IBAN / BIC',paypal:'Pagamento via PayPal',satispay:'Pagamento via Satispay',revolut:'Pagamento via Revolut',cash:'Pagamento in negozio',other:'Metodo di pagamento alternativo',beneficiary:'Beneficiario',copy:'Copia',copied:'Copiato!',bankTitle:'Bonifico bancario',cashTitle:'Pagamento in contanti',cashText:'I contanti sono accettati direttamente in negozio.',externalText:'Continuerai nell’app o nel sito del servizio di pagamento.',open:(x:string)=>`Apri ${x}`},
} as const;
function isRevolut(label:string|null){return /revolut/i.test(label??'')}
function description(pm:TenantPaymentMethod,t:typeof COPY.fr|typeof COPY.it){switch(pm.method){case'card':return t.card;case'bank_transfer':return t.bank;case'paypal':return t.paypal;case'satispay':return t.satispay;case'cash':return t.cash;case'other':return isRevolut(pm.label)?t.revolut:t.other;default:return t.other}}
function CopyValue({value,color,label,copiedLabel}:{value:string;color:string;label:string;copiedLabel:string}){const[copied,setCopied]=useState(false);return <button type="button" onClick={()=>{navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1500)}} className="flex min-h-12 w-full items-center justify-between gap-3 rounded-xl border px-3 text-left focus-visible:outline-none focus-visible:ring-2" style={{borderColor:hexToRgba(color,.28),'--tw-ring-color':color} as React.CSSProperties}><span className="min-w-0 break-all font-mono text-sm font-semibold text-gray-800">{value}</span><span className="flex shrink-0 items-center gap-1 text-xs font-semibold" style={{color}}>{copied?<IconCheck size={16}/>:<IconCopy size={16}/>} {copied?copiedLabel:label}</span></button>}

export function PaymentMethodsAccordion({paymentMethods,primaryColor,currency,lang,onClose}:{paymentMethods:TenantPaymentMethod[];primaryColor:string;currency:string;lang:Lang;onClose:()=>void}){
 const t=COPY[lang]; const[selected,setSelected]=useState<TenantPaymentMethod|null>(null);
 if(paymentMethods.length===0)return null;
 if(selected?.method==='card') return <CardQuickPay tenantColor={methodColor('card',primaryColor)} currency={currency} lang={lang} onBack={()=>setSelected(null)} onReturnToCard={onClose}/>;
 if(selected){const color=methodColor(selected.method,primaryColor);const meta=PAYMENT_METHOD_REGISTRY[selected.method];const Icon=PAYMENT_ICONS[meta.iconName];const title=selected.label??meta.label;const bank=selected.method==='bank_transfer';const cash=selected.method==='cash';const externalLink=selected.extra?.link||(selected.method==='satispay'?selected.value:null)||(selected.method==='paypal'&&selected.value&&!isEmailValue(selected.value)?selected.value:null);return <div><button type="button" onClick={()=>setSelected(null)} className="mb-5 flex min-h-11 items-center gap-2 rounded-lg px-1 text-sm font-medium text-gray-600 focus-visible:outline-none focus-visible:ring-2" style={{'--tw-ring-color':primaryColor} as React.CSSProperties}><IconArrowLeft size={18}/>{t.back}</button><div className="mb-6 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl text-white" style={{backgroundColor:color}}><Icon size={21}/></div><h2 className="text-2xl font-bold text-gray-900" style={{fontFamily:'var(--font-card-heading)'}}>{bank?t.bankTitle:cash?t.cashTitle:title}</h2></div>{cash?<div className="rounded-2xl border border-gray-100 bg-gray-50 p-5 text-sm leading-relaxed text-gray-600">{t.cashText}</div>:bank?<div className="space-y-5">{selected.extra?.beneficiary&&<div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">{t.beneficiary}</p><CopyValue value={selected.extra.beneficiary} color={color} label={t.copy} copiedLabel={t.copied}/></div>}{selected.value&&<div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">IBAN</p><CopyValue value={selected.value} color={color} label={t.copy} copiedLabel={t.copied}/></div>}{selected.extra?.bic&&<div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-400">BIC</p><CopyValue value={selected.extra.bic} color={color} label={t.copy} copiedLabel={t.copied}/></div>}{selected.extra?.link&&<a href={selected.extra.link} target="_blank" rel="noopener noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl font-semibold text-white" style={{backgroundColor:color}}><IconExternalLink size={18}/>{t.open(title)}</a>}</div>:<div className="space-y-5"><p className="text-sm leading-relaxed text-gray-500">{t.externalText}</p>{selected.method==='paypal'&&selected.value&&isEmailValue(selected.value)&&<CopyValue value={selected.value} color={color} label={t.copy} copiedLabel={t.copied}/>} {externalLink&&<a href={externalLink} target="_blank" rel="noopener noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl font-semibold text-white" style={{backgroundColor:color}}><IconExternalLink size={18}/>{t.open(title)}</a>}{selected.method==='other'&&!externalLink&&selected.value&&<p className="rounded-xl bg-gray-50 p-4 text-sm text-gray-600">{selected.value}</p>}</div>}</div>}
 return <div><button type="button" onClick={onClose} className="mb-5 flex min-h-11 items-center gap-2 rounded-lg px-1 text-sm font-medium text-gray-600 focus-visible:outline-none focus-visible:ring-2" style={{'--tw-ring-color':primaryColor} as React.CSSProperties}><IconArrowLeft size={18}/>{t.back}</button><h2 className="mb-5 text-2xl font-bold text-gray-900" style={{fontFamily:'var(--font-card-heading)'}}>{t.title}</h2><div className="space-y-2.5">{paymentMethods.map(pm=>{const meta=PAYMENT_METHOD_REGISTRY[pm.method];const Icon=PAYMENT_ICONS[meta.iconName];const color=methodColor(pm.method,primaryColor);return <button key={pm.id} type="button" onClick={()=>setSelected(pm)} className="flex min-h-16 w-full items-center gap-3 rounded-2xl border border-gray-200 bg-white p-3 text-left transition-shadow hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2" style={{'--tw-ring-color':primaryColor} as React.CSSProperties}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-white" style={{backgroundColor:color}}><Icon size={20}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-gray-900">{pm.label??meta.label}</span><span className="mt-0.5 block text-xs text-gray-500">{description(pm,t)}</span></span><IconChevronRight size={18} className="shrink-0 text-gray-300"/></button>})}</div></div>
}
