'use client';
import { useState } from 'react'; import { useRouter } from 'next/navigation'; import { IconPlus, IconTrash } from '@tabler/icons-react';
const fields=[['orders_count','Nombre de commandes'],['lifetime_value','Valeur client'],['average_order_value','Panier moyen'],['days_since_last_order','Jours depuis le dernier achat'],['created_at','Date de création'],['source','Source'],['marketing_consent','Consentement marketing'],['loyalty_points','Points fidélité'],['rfm_segment','Segment RFM'],['tag','Tag'],['favorite_category','Catégorie préférée'],['favorite_product','Produit préféré'],['event_participation','Participation événements']];
const operators=['=','!=','>','>=','<','<=','contains','not_contains','before','after','in','not_in'];
type Condition={field:string;operator:string;value:string};
export function SegmentBuilder(){const router=useRouter();const [open,setOpen]=useState(false);const [name,setName]=useState('');const [group,setGroup]=useState<'and'|'or'>('and');const [conditions,setConditions]=useState<Condition[]>([{field:'orders_count',operator:'>=',value:'2'}]);const [preview,setPreview]=useState<number|null>(null);const [error,setError]=useState('');
 const definition=()=>({operator:group,conditions:conditions.map(c=>({...c,value:['orders_count','lifetime_value','average_order_value','days_since_last_order','loyalty_points','event_participation'].includes(c.field)?Number(c.value):c.field==='marketing_consent'?c.value==='true':c.value}))});
 async function previewNow(){setError('');const r=await fetch('/api/admin/clients/segments/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({definition:definition()})});const j=await r.json();if(!r.ok)setError(j.error);else setPreview(j.count)}
 async function save(){const r=await fetch('/api/admin/clients/segments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,definition:definition()})});const j=await r.json();if(!r.ok){setError(j.error);return;}setOpen(false);router.refresh()}
 return <><button onClick={()=>setOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--admin-primary)] px-4 text-sm font-semibold text-white"><IconPlus size={18}/>Créer un segment</button>{open&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-4" onMouseDown={()=>setOpen(false)}><div onMouseDown={e=>e.stopPropagation()} className="max-h-[90vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 dark:bg-gray-900 sm:max-w-2xl sm:rounded-2xl"><h2 className="text-lg font-semibold">Créer un segment</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom du segment" className="mt-4 h-11 w-full rounded-xl border px-3 dark:bg-gray-950"/><div className="mt-4 flex gap-2 text-sm"><button onClick={()=>setGroup('and')} className={`rounded-lg px-3 py-2 ${group==='and'?'bg-violet-100 text-violet-800':'bg-gray-100'}`}>Toutes les conditions</button><button onClick={()=>setGroup('or')} className={`rounded-lg px-3 py-2 ${group==='or'?'bg-violet-100 text-violet-800':'bg-gray-100'}`}>Au moins une</button></div><div className="mt-3 space-y-2">{conditions.map((c,i)=><div key={i} className="grid gap-2 rounded-xl bg-gray-50 p-3 dark:bg-gray-800 sm:grid-cols-[1fr_120px_1fr_44px]"><select value={c.field} onChange={e=>setConditions(v=>v.map((x,n)=>n===i?{...x,field:e.target.value}:x))} className="h-11 rounded-lg border bg-white px-2 dark:bg-gray-950">{fields.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={c.operator} onChange={e=>setConditions(v=>v.map((x,n)=>n===i?{...x,operator:e.target.value}:x))} className="h-11 rounded-lg border bg-white px-2 dark:bg-gray-950">{operators.map(o=><option key={o}>{o}</option>)}</select><input value={c.value} onChange={e=>setConditions(v=>v.map((x,n)=>n===i?{...x,value:e.target.value}:x))} className="h-11 rounded-lg border px-2 dark:bg-gray-950"/><button onClick={()=>setConditions(v=>v.filter((_,n)=>n!==i))} className="flex h-11 items-center justify-center rounded-lg text-red-600" aria-label="Supprimer"><IconTrash size={18}/></button></div>)}</div><button onClick={()=>setConditions(v=>[...v,{field:'orders_count',operator:'>=',value:'1'}])} className="mt-2 min-h-11 text-sm font-semibold text-violet-700">+ Ajouter une condition</button>{preview!==null&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{preview} clients correspondent</p>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex gap-2"><button onClick={previewNow} className="min-h-11 flex-1 rounded-xl border px-4 font-semibold">Prévisualiser</button><button disabled={!name||conditions.length===0} onClick={save} className="min-h-11 flex-1 rounded-xl bg-[var(--admin-primary)] px-4 font-semibold text-white disabled:opacity-50">Créer</button></div></div></div>}</>}
